server:
  port: 1337

database:
  host: 127.0.0.1
  user: root
  pass: root
  db: kafka

spring:
  application:
    name: kafka-spring
  datasource:
    url: jdbc:mysql://${database.host}:3306/${database.db}?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.user}
    password: ${database.pass}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

job:
  process:
    limit: 99999999999999
    page-size: 30
  generate:
    limit: 99999999999999

kafka:
  bootstrap-servers: localhost:9092
  schema-registry-url: http://localhost:8081
  request.timeout: 30000

advertised:
  host:
    name: localhost
